/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_year17_analyse_ndk_sockets_LocalEchoActivity */

#ifndef _Included_com_year17_analyse_ndk_sockets_LocalEchoActivity
#define _Included_com_year17_analyse_ndk_sockets_LocalEchoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_year17_analyse_ndk_sockets_LocalEchoActivity
 * Method:    nativeStartLocalServer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_year17_analyse_1ndk_1sockets_LocalEchoActivity_nativeStartLocalServer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
