/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_year17_analyse_ndk_sockets_MainActivity */

#ifndef _Included_com_year17_analyse_ndk_sockets_MainActivity
#define _Included_com_year17_analyse_ndk_sockets_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_year17_analyse_ndk_sockets_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_year17_analyse_1ndk_1sockets_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_year17_analyse_ndk_sockets_MainActivity
 * Method:    stringFromSocket
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_year17_analyse_1ndk_1sockets_MainActivity_stringFromSocket
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
