/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_year17_analyse_ndk_sockets_ClientEchoActivity */

#ifndef _Included_com_year17_analyse_ndk_sockets_ClientEchoActivity
#define _Included_com_year17_analyse_ndk_sockets_ClientEchoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_year17_analyse_ndk_sockets_ClientEchoActivity
 * Method:    nativeStartTcpClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_year17_analyse_1ndk_1sockets_ClientEchoActivity_nativeStartTcpClient
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_year17_analyse_ndk_sockets_ClientEchoActivity
 * Method:    nativeStartUdpClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_year17_analyse_1ndk_1sockets_ClientEchoActivity_nativeStartUdpClient
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
